Algoritmo "ContarAte.."
//
// Descrição   : ESTRUTURAS DE REPETIÇÃO
// Autor(a)    : Jonathan
// Data atual  : 19/9/2022
Var
   Valor, Salto, contador:inteiro


Inicio
contador <- 0
Escreva ("Quer contar até quanto? ")
Leia (Valor)
escreva ("Qual será o valor do salto? ")
leia (Salto)
Enquanto (contador <= Valor) faca
         Escreval (contador)
         contador <- contador + Salto
FimEnquanto
escreva ("Fim da Contagem")


Fimalgoritmo