Algoritmo "NotaAluno"
//  
//  
Var
nome:caractere
Nota1,Nota2, Nota3, Nota4:inteiro

Inicio
nome <- "Jonathan"
Nota1 <- 6
Nota2 <- 9
Nota3 <- 10
Nota4 <- 9

escreval("----------------------")
escreval("  Instituto Go-IT ")
escreval("----------------------")
escreval("Nome: ",nome)
escreval("")
escreval("Nota 1=",Nota1)
escreval("Nota 2=",Nota2)
escreval("Nota 3=",Nota3)
escreval("Nota 4=",Nota4)
escreval("")
escreva ("----------------------")

Fimalgoritmo