Algoritmo "Exercicio 08"
//
//
Var
   n1: inteiro

   n2: inteiro

Inicio

   escreva ("Digite um número: ")

   leia (n1)

   escreva  ("Digite outro número: ")

   leia (n2)

   se (n1 > n2) então

      escreval("O primeiro valor é o maior")

   senao
      se (n1 = n2) entao

         escreval ("Não existe valor maior, os dois são iguais")

      senao

         escreval("O segundo valor é o maior")

      fimse

   fimse

Fimalgoritmo