Algoritmo "Exercicio 17"
// 

Var
  n:vetor[0..9] de inteiro


Inicio
      n[0] <-5
      
      n[1] <-3
      
      n[2] <-5
      
      n[3] <-3
      
      n[4] <-5
      
      n[5] <-3
      
      n[6] <-5
      
      n[7] <-3
      
      n[8] <-5
      
      n[9] <-3

      Escreva(n[0], n[1], n[2], n[3], n[4], n[5], n[6], n[7], n[8], n[9])


Fimalgoritmo