Algoritmo "Exercicio 04"
//  
//  
//
//

Var
   Aluno:caractere

   Nota1,Nota2,media:real

Inicio

   escreva ("Informe o nome do aluno:")

   leia (Aluno)

   escreval("")

   escreval("  Informe as notas")

   escreval("")

   escreva (" Nota 1:")

   leia (Nota1)

   escreval

   escreva (" Nota 2:")

   leia (Nota2)

   escreval

   media <- (Nota1+Nota2)/2

   escreval("A média entre ", Nota1, " e", Nota2, " é igual a ", media)


Fimalgoritmo